reorder
Signed-off-by: chipzoller <chipzoller@gmail.com>

diff --git a/cost-analyzer/templates/tests/basic-health.yaml b/cost-analyzer/templates/tests/basic-health.yaml
--- a/cost-analyzer/templates/tests/basic-health.yaml
+++ b/cost-analyzer/templates/tests/basic-health.yaml
@@ -1,32 +1,10 @@
 apiVersion: v1
-kind: Pod
+kind: ServiceAccount
 metadata:
-  name: basic-health
-  namespace: {{ .Release.Namespace }}
+  name: e2e-testing
   annotations:
     {{- include "kubecost.test.annotations" . | nindent 4 }}
-spec:
-  serviceAccountName: e2e-testing
-  restartPolicy: Never
-  containers:
-  - name: test-kubecost
-    image: alpine/k8s:1.26.9
-    command:
-      - /bin/sh
-    args:
-      - -c
-      - >-
-        svc=$(kubectl -n {{ .Release.Namespace }} get svc -l app.kubernetes.io/name=cost-analyzer -o json | jq -r .items[0].metadata.name);
-        echo Getting current Kubecost state.;
-        response=$(curl -sL http://${svc}:9090/model/getConfigs);
-        code=$(echo ${response} | jq .code);
-        if [ "$code" -eq 200 ]; then
-          echo "Got Kubecost working configuration. Successful."
-          exit 0
-        else 
-          echo "Failed to fetch Kubecost configuration. Response was $response"
-          exit 1
-        fi
+  namespace: {{ .Release.Namespace }}
 ---
 apiVersion: rbac.authorization.k8s.io/v1
 kind: Role
@@ -57,9 +35,31 @@ roleRef:
   apiGroup: rbac.authorization.k8s.io
 ---
 apiVersion: v1
-kind: ServiceAccount
+kind: Pod
 metadata:
-  name: e2e-testing
+  name: basic-health
+  namespace: {{ .Release.Namespace }}
   annotations:
     {{- include "kubecost.test.annotations" . | nindent 4 }}
-  namespace: {{ .Release.Namespace }}
+spec:
+  serviceAccountName: e2e-testing
+  restartPolicy: Never
+  containers:
+  - name: test-kubecost
+    image: alpine/k8s:1.26.9
+    command:
+      - /bin/sh
+    args:
+      - -c
+      - >-
+        svc=$(kubectl -n {{ .Release.Namespace }} get svc -l app.kubernetes.io/name=cost-analyzer -o json | jq -r .items[0].metadata.name);
+        echo Getting current Kubecost state.;
+        response=$(curl -sL http://${svc}:9090/model/getConfigs);
+        code=$(echo ${response} | jq .code);
+        if [ "$code" -eq 200 ]; then
+          echo "Got Kubecost working configuration. Successful."
+          exit 0
+        else 
+          echo "Failed to fetch Kubecost configuration. Response was $response"
+          exit 1
+        fi
